=== jmcanterafonseca-iota/ebsi-schemas/ebsi-VerifiableAuthorisation-01.json
{
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "EBSI Verifiable Authorisation",
        "description": "Schema of an EBSI Verifiable Authorisation",
        "type": "object",
        "properties": {
                "@context": {
                        "description": "Defines semantic context of the Verifiable Authorisation",
                        "type": "array",
                        "items": {
                                "type": "string",
                                "format": "uri"
                        }
                },
                "id": {
                        "description": "Defines unique identifier of the Verifiable Authorisation",
                        "type": "string"
                },
                "type": {
                        "description": "Defines the Verifiable Credential type",
                        "type": "array",
                        "items": {
                                "type": "string"
                        }
                },
                "issuer": {
                        "description": "Defines the issuer of the Verifiable Authorisation",
                        "type": "string"
                },
                "issuanceDate": {
                        "description": "Defines when the Verifiable Authorisation was issued",
                        "type": "string",
                        "format": "date-time"
                },
                "validFrom": {
                        "description": "Defines the date and time, when the Verifiable Authorisation becomes valid",
                        "type": "string",
                        "format": "date-time"
                },
                "expirationDate": {
                        "description": "Defines the date and time, when the Verifiable Authorisation expires",
                        "type": "string",
                        "format": "date-time"
                },
                "credentialSubject": {
                        "description": "Defines information about the subject that is described by the Verifiable Authorisation",
                        "type": "object",
                        "properties": {
                                "id": {
                                        "description": "DID of the subject",
                                        "type": "uri"
                                }
                        },
                        "required": [
                                "id"
                        ]
                },
                "credentialStatus": {
                        "description": "Contains information about how to verify the status of the Verifiable Authorisation (via the Revocation and Endorsement Registry, RER)",
                        "type": "object",
                        "properties": {
                                "id": {
                                        "description": "References record in the Revocation and Endorsement Registry (RER) to enable verification of a Verifiable Authorisationâ€™s validity",
                                        "type": "string"
                                },
                                "type": {
                                        "description": "Defines the Verifiable Credential status type",
                                        "type": "string"
                                }
                        },
                        "required": [
                                "id",
                                "type"
                        ]
                },
                "credentialSchema": {
                        "description": "Contains information about the credential schema (template) on which the Verifiable Authorisation is based",
                        "type": "object",
                        "properties": {
                                "id": {
                                        "description": "References the credential schema (template) stored on the (relevant) Trusted Schemas Registry (TSR) on which the Verifiable Authorisation is based",
                                        "type": "string",
                                        "format": "uri"
                                },
                                "type": {
                                        "description": "Defines credential schema type",
                                        "type": "string",
                                        "enum": ["FullJsonSchemaValidator2021"]
                                }
                        },
                        "required": [
                                "id",
                                "type"
                        ]
                },
                "evidence": {
                        "description": "Contains information about the process which resulted in the issuance of the Verifiable Authorisation",
                        "type": "object",
                        "properties": {
                                "id": {
                                        "description": "References the issuance policy stored on the (relevant) Trusted Schemas Registry (TSR) that has been followed for issuing the Verifiable Authorisation",
                                        "type": "string"
                                },
                                "type": {
                                        "description": "Defines the evidence type",
                                        "type": "array",
                                        "items": {
                                                "type": "string"
                                        }
                                }
                        }
                },
                "proof": {
                        "description": "Contains information about the proof",
                        "type": "object",
                        "properties": {
                                "type": {
                                        "description": "Defines the proof type",
                                        "type": "string"
                                },
                                "proofPurpose": {
                                        "description": "Defines the purpose of the proof",
                                        "type": "string"
                                },
                                "created": {
                                        "description": "Defines the date and time, when the proof has been created",
                                        "type": "string",
                                        "format": "date-time"
                                },
                                "verificationMethod": {
                                        "description": "Contains information about the verification method / proof mechanisms",
                                        "type": "string"
                                },
                                "jws": {
                                        "description": "Defines the proof value in JWS format",
                                        "type": "string"
                                }
                        },
                        "required": [
                                "type",
                                "proofPurpose",
                                "created",
                                "verificationMethod",
                                "jws"
                        ]
                }
        },
        "required": [
                "@context",
                "id",
                "type",
                "issuer",
                "issuanceDate",
                "validFrom",
                "credentialSubject",
                "credentialSchema"
        ]
}

=== jmcanterafonseca-iota/ebsi-schemas/schemas/ebsi-attestation/2021-11/examples/with-proof.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://essif.europa.eu/schemas/vc/2020/v1"
  ],
  "id": "https://essif.europa.eu/tsr/53",
  "type": ["VerifiableCredential", "VerifiableAttestation"],
  "issuer": "did:ebsi:00001234",
  "issuanceDate": "2020-06-22T14:11:44Z",
  "credentialSubject": {
    "id": "did:ebsi:00001235",
    "authorizationClaims": {
      "credentialSchemaId": ["https://url.to/tsr/schema1"]
    }
  },
  "expirationDate": "2024-06-22T14:11:44Z",
  "validFrom": "2021-11-01T00:00:00Z",
  "credentialStatus": {
    "id": "https://essif.europa.eu/status/45",
    "type": "CredentialsStatusList2020"
  },
  "credentialSchema": {
    "id": "https://essif.europa.eu/tsr-123/verifiableattestation.json",
    "type": "FullJsonSchemaValidator2021"
  },
  "proof": {
    "type": "EidasSeal2019",
    "created": "2019-06-22T14:11:44Z",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "http://uri-to-verification-method",
    "jws": "eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..TCYt5X",
    "proofValue": "BD21J4fdlnBvBA+y6D...fnC8Y="
  }
}
